name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ 允许 actions 写入 gh-pages 分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ 防止 token 冲突

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'     # ✅ 必须设置 user
          user_email: 'github-actions[bot]@users.noreply.github.com'
